default: &default
  adapter: postgresql
  database: pruebarails
  username: postgres
  password: postgres
  pool: 5
  encoding: unicode
  host: postgres

development:
  <<: *default
  database: pruebarails

test:
  <<: *default
  database: preubarails_test

